### ISSUE TITLE
Test failure on master: email_address_with_name

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/heya#156]
It looks like Rails < 6.1 does not support `email_address_with_name`. I'm not sure why the tests didn't run on the PR (I thought they had).

@feliperaul any idea of the best way to fix this?

```
Error:
[175](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:175)
Heya::Campaigns::Actions::EmailTest#test_to_field:
[176](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:176)
NoMethodError: undefined method `email_address_with_name' for #<Heya::CampaignMailer:0x0000555d9c176228>
[177](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:177)
    /home/runner/work/heya/heya/app/mailers/heya/campaign_mailer.rb:60:in `to_address'
[178](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:178)
    /home/runner/work/heya/heya/app/mailers/heya/campaign_mailer.rb:29:in `build'
[179](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:179)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.4.4/lib/abstract_controller/base.rb:195:in `process_action'
[180](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:180)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.4.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[181](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:181)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:101:in `run_callbacks'
[182](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:182)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
[183](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:183)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.4.4/lib/abstract_controller/base.rb:136:in `process'
[184](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:184)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/rescuable.rb:25:in `block in process'
[185](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:185)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
[186](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:186)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/rescuable.rb:24:in `process'
[187](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:187)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.4.4/lib/action_view/rendering.rb:39:in `process'
[188](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:188)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/base.rb:637:in `block in process'
[189](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:189)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications.rb:180:in `block in instrument'
[190](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:190)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[191](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:191)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.4/lib/active_support/notifications.rb:180:in `instrument'
[192](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:192)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/base.rb:636:in `process'
[193](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:193)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/parameterized.rb:143:in `block in processed_mailer'
[194](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:194)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/parameterized.rb:141:in `tap'
[195](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:195)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/parameterized.rb:141:in `processed_mailer'
[196](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:196)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/message_delivery.rb:30:in `__getobj__'
[197](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:197)
    /opt/hostedtoolcache/Ruby/2.7.5/x64/lib/ruby/2.7.0/delegate.rb:80:in `method_missing'
[198](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:198)
    /home/runner/work/heya/heya/test/lib/heya/campaigns/actions/email_test.rb:36:in `block (2 levels) in <class:EmailTest>'
[199](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:199)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.4.4/lib/active_job/test_helper.rb:584:in `perform_enqueued_jobs'
[200](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:200)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.4/lib/action_mailer/test_helper.rb:37:in `assert_emails'
[201](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:201)
    /home/runner/work/heya/heya/test/lib/heya/campaigns/actions/email_test.rb:35:in `block in <class:EmailTest>'
[202](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:202)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:98:in `block (3 levels) in run'
[203](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:203)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:195:in `capture_exceptions'
[204](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:204)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:95:in `block (2 levels) in run'
[205](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:205)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:281:in `time_it'
[206](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:206)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:94:in `block in run'
[207](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:207)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
[208](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:208)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:221:in `with_info_handler'
[209](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:209)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:93:in `run'
[210](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:210)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:1042:in `run_one_method'
[211](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:211)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:350:in `run_one_method'
[212](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:212)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:337:in `block (2 levels) in run'
[213](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:213)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:336:in `each'
[214](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:214)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:336:in `block in run'
[215](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:215)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
[216](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:216)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:363:in `with_info_handler'
[217](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:217)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:335:in `run'
[218](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:218)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.4/lib/rails/test_unit/line_filtering.rb:10:in `run'
[219](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:219)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `block in __run'
[220](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:220)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `map'
[221](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:221)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `__run'
[222](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:222)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:146:in `run'
[223](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:223)
    /home/runner/work/heya/heya/gemfiles/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:73:in `block in autorun'
[224](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:224)

[225](https://github.com/honeybadger-io/heya/runs/5043231699?check_suite_focus=true#step:7:225)
rails test /home/runner/work/heya/heya/test/lib/heya/campaigns/actions/email_test.rb:25
```

**Comment by feliperaul** [comment]
@joshuap Sorry for this, I ran the test suite and it was all green. 

The `email_address_with_name` is very concise, it actually uses the Mail gem for the heavy lifting:

```
def email_address_with_name(address, name)
  Mail::Address.new.tap do |builder|
    builder.address = address
    builder.display_name = name
  end.to_s
end
```

Since in Rails this is defined as class method in `ActionMailer::Base`, what do you think about adding this as a class method in `Heya::CampaignMailer` ?

**Comment by joshuap** [comment]
> @joshuap Sorry for this, I ran the test suite and it was all green.
> 
> The `email_address_with_name` is very concise, it actually uses the Mail gem for the heavy lifting:
> 
> ```
> def email_address_with_name(address, name)
>   Mail::Address.new.tap do |builder|
>     builder.address = address
>     builder.display_name = name
>   end.to_s
> end
> ```
> 
> Since in Rails this is defined as class method in `ActionMailer::Base`, what do you think about adding this as a class method in `Heya::CampaignMailer` ?

I'm good with that. You might add a comment that says we can remove it once we drop support for Rails 6.0 👍

**Comment by feliperaul** [comment]
@joshuap Sent a PR
